# -*- coding: utf-8 -*-
"""Copy of python asignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqpkVY2IcVbw3SoMQYoLKDwdMkkP6esY
"""

node1 = {
    "name": "Julius Meteur Koshal",
    "adm_no": "CIT/00085/024",
    "grades": ["'CIR205'(85)","'MMA227'(90)","'CIS221'(78)" , "'CIM201'(90)","'CIT207'(84)"],
    "next": None
}


node1["next"] = None

head = node1


def print_list(head):
    current = head
    while current is not None:
        print(f"Name: {current['name']}, Adm No: {current['adm_no']}, Grades: {current['grades']}")
        current = current["next"]
print_list(head)